### ISSUE TITLE
Conflict with EntityTextureFeatures

### ISSUE THREAD

**Issue by CompeyDev** [MCLegoMan/Perspective#11]
[Entity Model Features](https://github.com/Traben-0/Entity_Model_Features) is conflicting with [Perspective](https://github.com/mclegoman/perspective).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_4606::emf$markEyeLight with priority 1000 cannot inject into net/minecraft/class_4606::method_4199(Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILnet/minecraft/class_1297;FFFFFF)V merged by com.mclegoman.perspective.mixin.client.textured_entity.minecraft.EyesFeatureRendererMixin with priority 10000 [PREINJECT Applicator Phase -> entity_model_features-common.mixins.json:rendering.MixinEyesFeatureRenderer from mod entity_model_features -> Prepare Injections ->  -> modify$beo000$entity_model_features$emf$markEyeLight(I)I -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:306)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:241)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(Unknown Source)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_5619.<clinit>(class_5619.java:42)
	at net.minecraft.class_898.method_14491(class_898.java:415)
	at net.minecraft.class_4013.method_29490(class_4013.java:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1283)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

## Mod list
```
- appleskin 2.5.1+mc1.20.3
- architectury 11.1.17
- badoptimizations 2.1.1
- balm-fabric 9.0.8
- bedrodium 0.2.3
- betterhurtcam 1.7.0+mc1.20.3
- betterpingdisplay 1.1.1
- bettershields 1.1.0+mc1.20.3
- c2me 0.2.0+alpha.11.67
- c2me-base 0.2.0+alpha.11.67 via c2me
- c2me-client-uncapvd 0.2.0+alpha.11.67 via c2me
- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.67 via c2me
- c2me-fixes-general-threading-issues 0.2.0+alpha.11.67 via c2me
- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.67 via c2me
- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.67 via c2me
- c2me-notickvd 0.2.0+alpha.11.67 via c2me
- c2me-opts-allocs 0.2.0+alpha.11.67 via c2me
- c2me-opts-chunk-access 0.2.0+alpha.11.67 via c2me
- c2me-opts-chunkio 0.2.0+alpha.11.67 via c2me
- c2me-opts-math 0.2.0+alpha.11.67 via c2me
- c2me-opts-scheduling 0.2.0+alpha.11.67 via c2me
- c2me-opts-worldgen-general 0.2.0+alpha.11.67 via c2me
- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.67 via c2me
- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.67 via c2me
- c2me-rewrites-chunkio 0.2.0+alpha.11.67 via c2me
- c2me-server-utils 0.2.0+alpha.11.67 via c2me
- c2me-threading-chunkio 0.2.0+alpha.11.67 via c2me
- c2me-threading-lighting 0.2.0+alpha.11.67 via c2me
- c2me-threading-worldgen 0.2.0+alpha.11.67 via c2me
- caffeineconfig 1.3.0+1.17 via sodium-extra
- calcmod fabric-1.20.2-1.3.1
- cat_jam 1.2.1
- chat_heads 0.10.32
- chatanimation 1.0.5
- citresewn 1.1.4-dicedpixels+1.20.4
- citresewn-defaults 1.1.4-dicedpixels+1.20.4 via citresewn
- clientarguments 1.6 via calcmod
- clienttweaks 13.0.2
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 13.0.121
- club_minnced_discord-rpc-release v3.4.0 via vanillarpc
- club_minnced_java-discord-rpc 2.0.2 via vanillarpc
- com_akuleshov7_ktoml-core-jvm 0.5.1 via zoomify
- com_electronwill_night-config_core 3.6.5 via c2me
- com_electronwill_night-config_toml 3.6.5 via c2me
- com_eliotlash_mclib_mclib 20 via geckolib
- com_github_mclegoman_releasetypeutils 2.1.0 via perspective
- com_google_code_findbugs_jsr305 3.0.2 via viafabricplus
- com_ibm_async_asyncutil 0.1.0 via c2me
- com_moandjiezana_toml_toml4j 0.7.2 via ukulib
- com_noxcrew_noxesium_api_ 1.2.2+f65a08b via noxesium
- com_twelvemonkeys_common_common-image 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_common_common-io 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_common_common-lang 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_imageio_imageio-core 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_imageio_imageio-metadata 3.10.0 via yet_another_config_lib_v3
- com_twelvemonkeys_imageio_imageio-webp 3.10.0 via yet_another_config_lib_v3
- com_vdurmont_semver4j 3.1.0 via viafabricplus
- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT via krypton
- com_viaversion_viabackwards-common 4.10.0 via viafabricplus
- com_viaversion_viaversion-common 4.10.0 via viafabricplus
- conditional-mixin 0.3.2 via moreculling
- continuity 3.0.0-beta.4+1.20.2
- controlling 15.0.5
- crowdin-translate 1.4+1.19.3 via sodium-extra
- custom_hud 3.3.2+1.20.4
- dark-loading-screen 1.6.14
- de_florianmichael_classic4j 2.0.2 via viafabricplus
- debugify 1.20.4+1.1
- dev_isxander_settxi_settxi-core 2.10.6 via zoomify
- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6 via zoomify
- early-loading-screen 0.5.0
- entity_model_features 2.0.2
- entity_texture_features 6.0.1
- entityculling 1.6.4
- essential-container 1.0.0
- essential-loader 1.2.1 via essential-container
- fabric-api 0.97.0+1.20.4
- fabric-api-base 0.4.37+78d798af4f via fabric-api
- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f via fabric-api
- fabric-biome-api-v1 13.0.17+78d798af4f via fabric-api
- fabric-block-api-v1 1.0.17+3e2216cb4f via fabric-api
- fabric-block-view-api-v2 1.0.5+78d798af4f via fabric-api
- fabric-blockrenderlayer-v1 1.1.47+78d798af4f via fabric-api
- fabric-client-tags-api-v1 1.1.8+78d798af4f via fabric-api
- fabric-command-api-v1 1.2.42+f71b366f4f via fabric-api
- fabric-command-api-v2 2.2.21+78d798af4f via fabric-api
- fabric-commands-v0 0.2.59+df3654b34f via fabric-api
- fabric-containers-v0 0.1.87+df3654b34f via fabric-api
- fabric-content-registries-v0 5.0.16+78d798af4f via fabric-api
- fabric-convention-tags-v1 1.5.11+78d798af4f via fabric-api
- fabric-crash-report-info-v1 0.2.24+78d798af4f via fabric-api
- fabric-data-attachment-api-v1 1.1.5+b90db5744f via fabric-api
- fabric-data-generation-api-v1 13.2.5+5c0133444f via fabric-api
- fabric-dimensions-v1 2.1.62+78d798af4f via fabric-api
- fabric-entity-events-v1 1.6.2+09fc25014f via fabric-api
- fabric-events-interaction-v0 0.7.2+389931eb4f via fabric-api
- fabric-events-lifecycle-v0 0.2.75+df3654b34f via fabric-api
- fabric-game-rule-api-v1 1.0.47+78d798af4f via fabric-api
- fabric-item-api-v1 2.3.0+bcdd12964f via fabric-api
- fabric-item-group-api-v1 4.0.27+ee30b13a4f via fabric-api
- fabric-key-binding-api-v1 1.0.42+78d798af4f via fabric-api
- fabric-keybindings-v0 0.2.40+df3654b34f via fabric-api
- fabric-language-kotlin 1.10.19+kotlin.1.9.23
- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f via fabric-api
- fabric-loot-api-v2 2.1.10+78d798af4f via fabric-api
- fabric-message-api-v1 6.0.6+78d798af4f via fabric-api
- fabric-mining-level-api-v1 2.1.66+78d798af4f via fabric-api
- fabric-model-loading-api-v1 1.0.9+78d798af4f via fabric-api
- fabric-models-v0 0.4.8+9386d8a74f via fabric-api
- fabric-networking-api-v1 3.1.8+2e5ac5484f via fabric-api
- fabric-object-builder-api-v1 13.1.0+dba1195c4f via fabric-api
- fabric-particles-v1 1.1.8+78d798af4f via fabric-api
- fabric-permissions-api-v0 0.3-SNAPSHOT via servercore
- fabric-recipe-api-v1 2.0.21+78d798af4f via fabric-api
- fabric-registry-sync-v0 4.0.20+ee30b13a4f via fabric-api
- fabric-renderer-api-v1 3.2.5+78d798af4f via fabric-api
- fabric-renderer-indigo 1.5.5+78d798af4f via fabric-api
- fabric-renderer-registries-v1 3.2.54+df3654b34f via fabric-api
- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f via fabric-api
- fabric-rendering-fluids-v1 3.1.2+e761c6694f via fabric-api
- fabric-rendering-v0 1.1.57+df3654b34f via fabric-api
- fabric-rendering-v1 3.2.1+6fd945a04f via fabric-api
- fabric-resource-conditions-api-v1 2.3.15+78d798af4f via fabric-api
- fabric-resource-loader-v0 0.11.21+ee30b13a4f via fabric-api
- fabric-screen-api-v1 2.0.18+78d798af4f via fabric-api
- fabric-screen-handler-api-v1 1.3.56+78d798af4f via fabric-api
- fabric-simplelibs 2.0.0 via perspective
- fabric-sound-api-v1 1.0.18+78d798af4f via fabric-api
- fabric-transfer-api-v1 4.0.12+90f2d7b14f via fabric-api
- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f via fabric-api
- fabricloader 0.15.11
- fastipping 1.0.1
- ferritecore 6.0.3
- feytweaks 1.20.4-1.2.8
- flow 1.5.0+1.20.4
- fullscreeno 1.0.0
- gammautils 1.7.19
- geckoanimfix 1.0.0
- geckolib 4.4.4
- gs_mclo_java_mclogs-java 2.1.1 via ukulib
- healthindicator 1.3.0+mc1.20.3
- idletweaks 1.0.8
- immediatelyfast 1.2.13+1.20.4
- indium 1.0.30+mc1.20.4
- inventoryhud 3.4.19
- io_github_douira_glsl-transformer 2.0.0-pre13 via iris
- io_jsonwebtoken_jjwt-api 0.12.5 via viafabricplus
- io_jsonwebtoken_jjwt-gson 0.12.5 via viafabricplus
- io_jsonwebtoken_jjwt-impl 0.12.5 via viafabricplus
- iris 1.7.0+mc1.20.4
- isxander-main-menu-credits 1.1.2
- java 21
- krypton 0.2.6
- litematica 0.17.2
- lithium 0.12.1
- malilib 0.18.1
- mica 1.0.1
- midnightlib 1.5.3
- minecraft 1.20.4
- mixin-conflict-helper 1.2.0
- mixinextras 0.3.5 via fabricloader
- mixinsquared 0.1.1 via moreculling
- mixtape 1.6.2
- modelfix 1.14
- modernfix 5.17.0+mc1.20.4
- modmenu 9.2.0-beta.2
- moreculling 1.20.4-0.24.0
- mousetweaks 2.26
- mru 0.4.0+1.20.4
- narrus_yeetus 1.1.0
- net_bytebuddy_byte-buddy-agent 1.14.0 via early-loading-screen
- net_jodah_expiringmap 0.5.10 via viafabricplus
- net_lenni0451_commons_httpclient 1.4.1 via viafabricplus
- net_lenni0451_mcping 1.4.0 via viafabricplus
- net_lenni0451_mcstructs-bedrock_forms 1.2.0 via viafabricplus
- net_lenni0451_mcstructs-bedrock_text 1.2.0 via viafabricplus
- net_lenni0451_reflect 1.3.2 via immediatelyfast
- net_minecraftforge_unsafe 0.9.2 via early-loading-screen
- net_objecthunter_exp4j 0.4.8 via c2me
- net_raphimc_minecraftauth 4.0.0 via viafabricplus
- net_raphimc_viaaprilfools 2.0.11 via viafabricplus
- net_raphimc_viabedrock 0.0.6-SNAPSHOT via viafabricplus
- net_raphimc_vialegacy 2.2.22 via viafabricplus
- net_raphimc_vialoader 2.2.13 via viafabricplus
- nmuk 1.1.1+mc1.20.4
- no-telemetry 1.8.0
- nochatreports 1.20.4-v2.6.1
- notenoughanimations 1.7.3
- nowheel 1.2.2+mc1.20.2
- noxesium 1.2.2+f65a08b
- obsidianui 0.2.4+mc1.20.4
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.11.1 via iris
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR3-SNAPSHOT via viafabricplus
- org_iq80_leveldb_leveldb 0.12 via viafabricplus
- org_iq80_leveldb_leveldb-api 0.12 via viafabricplus
- org_jetbrains_kotlin_kotlin-reflect 1.9.23 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.9.23 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3 via fabric-language-kotlin
- org_lz4_lz4-pure-java 1.8.0 via viafabricplus
- org_mariuszgromada_math_mathparser_org-mxparser 5.0.6 via calcmod
- org_quiltmc_parsers_gson 0.2.1 via yet_another_config_lib_v3
- org_quiltmc_parsers_json 0.2.1 via yet_another_config_lib_v3
- org_threadly_threadly 7.0 via c2me
- org_yaml_snakeyaml 2.2 via servercore
- persistentgamemodeswitcher 1.0.3.9
- perspective 1.2.1-release.2
- placeholder-api 2.3.0+1.20.3 via servercore
- potioncounter 1.4.0+mc1.20.3
- reeses-sodium-options 1.7.2+mc1.20.4-build.102
- rrls 4.0.3+mc1.20.4-fabric
- ryoamiclights 0.2.5+mc1.20.4
- screenshotclipboard 1.0.9
- searchables 1.0.6
- servercore 1.5.0+1.20.4
- shulkerboxtooltip 4.0.8+1.20.4
- sodium 0.5.8+mc1.20.4
- sodium-extra 0.5.4+mc1.20.4-build.116
- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2 via servercore
- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2 via servercore
- sspb 3.3.0
- tia 1.20-1.1
- totemcounter 1.4.0+mc1.20.3
- ukulib 1.1.2+1.20.4
- ukus-armor-hud 0.4.2+mc1.20.3
- vanillarpc 1.2
- viafabricplus 3.1.1
- vmp 0.2.0+beta.7.139
- voicechat 1.20.4-2.5.13
- waveycapes 1.4.6
- whoami 1.0
- whyamionfire 1.3.1
- xaerominimapfair 24.1.1
- yet_another_config_lib_v3 3.4.2+1.20.4-fabric
- yosbr 0.1.2
- zergatulfreecam 2.2.1
- zoomify 2.13.2
- essential 1.3.2.2+gc6bc4f09d7
- vigilance 297
- universalcraft 337
- elementa 638
- org_jetbrains_annotations 23.0.0
```

## Game info
Minecraft Version: 1.20.4
Fabric Loader Version: 0.15.11

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)* (sorry, a bit lazy to draft my own :P)

**Comment by mclegoman** [comment]
Thanks for your report! There should be a fix within the next hour!

**Comment by mclegoman** [comment]
I've fixed the issue preventing the game from loading, you'll be able to run the mods together now.
If you find any other issues feel free to open another thread!

[https://modrinth.com/mod/mclegoman-perspective/version/1.2.2-release.1+1.20.3-4](https://modrinth.com/mod/mclegoman-perspective/version/1.2.2-release.1+1.20.3-4)

**Comment by CompeyDev** [comment]
Thank you very much!

**Comment by mclegoman** [comment]
No problem!
